name: job_quest
description: "JobQuest is a mobile application built with Flutter and powered by AppWrite, designed to simplify job searching. It helps users find job opportunities easily, apply for positions, and track their application status, all within one intuitive platform."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

